src/ClothesBox.Web/Models/Layout/RightSideBarViewModel.cs
using ClothesBox.Configuration.Ui;

namespace ClothesBox.Web.Models.Layout
{
    public class RightSideBarViewModel
    {
        public UiThemeInfo CurrentTheme { get; set; }
    }
}

src/ClothesBox.Web/Models/Layout/SideBarNavViewModel.cs
using Abp.Application.Navigation;

namespace ClothesBox.Web.Models.Layout
{
    public class SideBarNavViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

src/ClothesBox.Web/Models/Layout/SideBarUserAreaViewModel.cs
using ClothesBox.Sessions.Dto;

namespace ClothesBox.Web.Models.Layout
{
    public class SideBarUserAreaViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }
    }
}

src/ClothesBox.Web/Controllers/LayoutController.cs
using System.Linq;
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using ClothesBox.Configuration;
using ClothesBox.Configuration.Ui;
using ClothesBox.Sessions;
using ClothesBox.Web.Models;
using ClothesBox.Web.Models.Layout;

namespace ClothesBox.Web.Controllers
{
    public class LayoutController : ClothesBoxControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager,
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult SideBarNav(string activeMenu = "")
        {
            var model = new SideBarNavViewModel
            {
                MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                ActiveMenuItemName = activeMenu
            };

            return PartialView("_SideBarNav", model);
        }

        [ChildActionOnly]
        public PartialViewResult ToolbarWrapper()
        {
            return PartialView("_ToolbarWrapper");
        }

        [ChildActionOnly]
        public PartialViewResult SideBarUserArea()
        {
            var model = new SideBarUserAreaViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return PartialView("_SideBarUserArea", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages()
            };

            return PartialView("_LanguageSelection", model);
        }

        [ChildActionOnly]
        public PartialViewResult RightSideBar()
        {
            var themeName = SettingManager.GetSettingValue(AppSettingNames.UiTheme);

            var viewModel = new RightSideBarViewModel
            {
                CurrentTheme = UiThemes.All.FirstOrDefault(t => t.CssClass == themeName)
            };

            return PartialView("_RightSideBar", viewModel);
        }
    }
}

src/ClothesBox.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Configuration
@using Abp.Timing
@using ClothesBox
@using ClothesBox.Configuration
@using Abp.Dependency
@using Abp.Web.Mvc.Alerts
@using Abp.Web.Mvc.Extensions
@{
    Layout = null;
    SetAntiForgeryCookie();
    var uiTheme = SettingManager.GetSettingValue(AppSettingNames.UiTheme);
    AlertList alerts = null;
    IocManager.Instance.Using<IAlertManager>(alertManager => alerts = alertManager.Alerts);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">
    <link href="assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css" />
    <link href="assets/css/style.bundle.css" rel="stylesheet" type="text/css" />

    <title>ClothesBox</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/assets/plugins/global/plugins.bundle.css")
    @Styles.Render("~/assets/css/style.bundle.css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>
</head>
@*<body class="@("theme-" + uiTheme)">*@

<body id="kt_body" class="header-fixed header-tablet-and-mobile-fixed toolbar-enabled toolbar-fixed aside-enabled aside-fixed" style="--kt-toolbar-height:55px;--kt-toolbar-height-tablet-and-mobile:55px">

     @*Page Loader*@ 
    @*<div class="page-loader-wrapper">
            <div class="loader">
                <div class="preloader">
                    <div class="spinner-layer pl-red">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div>
                        <div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
                <p>Please wait...</p>
            </div>
        </div>*@
    @*#END# Page Loader*@

    <!--begin::Root-->
    <div class="d-flex flex-column flex-root">
        <!--begin::Page-->
        <div class="page d-flex flex-row flex-column-fluid">
            <!--begin::Aside-->
            <div id="kt_aside" class="aside aside-dark aside-hoverable" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_mobile_toggle">
                @Html.Action("SideBarNav", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </div>
            <!--end::Aside-->

            <!--begin::Wrapper-->
            <div class="wrapper d-flex flex-column flex-row-fluid" id="kt_wrapper">
                <!--begin::Header-->
                <div id="kt_header" class="header align-items-stretch">
                        <div class="container-fluid d-flex align-items-stretch justify-content-between">
                            <div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1">
                                <div class="d-flex align-items-stretch" id="kt_header_nav">
                                    <h1 style="margin: 20px">@ViewBag.ActiveMenu</h1>
                                </div>
                                @Html.Action("ToolbarWrapper", "Layout")
                            </div>
                    </div>
                </div>
                <!--end::Header-->

                <!--<section>
                    <!--<aside id="leftsidebar" class="sidebar">-->
                        <!--@*@Html.Action("SideBarUserArea", "Layout")*@
                        @*@Html.Action("SideBarNav", "Layout", new { activeMenu = ViewBag.ActiveMenu })*@
                        @*Footer*@
                        @*<div class="legal">
                            <div class="copyright">
                                &copy; @DateTime.Now.Year <a href="javascript:void(0);">ClothesBox</a>.
                            </div>
                            <div class="version">
                                <b>Version </b> @AppVersionHelper.Version [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]
                            </div>
                        </div>*@
                        @*#Footer*@-->
                    <!--<!--</aside>-->
                    <!--@*@Html.Action("RightSideBar", "Layout")*@
                </section>-->
                
                <div class="content d-flex flex-column flex-column-fluid" id="kt_content">
                    @if (alerts.Any())
                    {
                        <div id="AbpPageAlerts">
                            @foreach (var alertMessage in alerts)
                            {
                                <div class="alert alert-@alertMessage.Type.ToString().ToLower() @(alertMessage.Dismissible ? "alert-dismisable" : "")" role="alert">
                                    <h4 class="alert-heading">
                                        @alertMessage.Title
                                        @if (alertMessage.Dismissible)
                                        {
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        }
                                    </h4>
                                    <p>@alertMessage.Text</p>
                                </div>
                            }
                        </div>
                    }

                    @RenderBody()
                </div>

            </div>
            <!--end::Wrapper-->

        </div>
        <!--end::Page-->
    </div>
    <!--end::Root-->

    @*@Scripts.Render("~/Bundles/vendor/js/bottom")*@

    @Html.IncludeScript("~/assets/plugins/global/plugins.bundle.js")
    @Html.IncludeScript("~/assets/js/scripts.bundle.js")

    @*<script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>*@

    @*Dynamic scripts of ABP system (They are created on runtime and can not be bundled)*@
    @*<script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>*@
    @*<script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>*@

    @*SignalR scripts*@
    @*<script src="~/signalr/hubs"></script>*@
    @*@Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")*@

    @*View specific scripts*@
    @RenderSection("scripts", required: false)
</body>
</html>